application:
  url: https://prolog.techcourse.co.kr

spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comment: false
  flyway:
    out-of-order: false
